name:                okapi
version:             0.1.0.0
github:              "githubuser/okapi"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/okapi#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- base64
- bytestring
- http-api-data
- http-types
- mmorph
- mtl
- random
- wai
- warp
- warp-tls
- text
- transformers

library:
  source-dirs: src

executables:
  realworld-exe:
    main:                Main.hs
    source-dirs:         examples/realworld
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - okapi
    - containers
    - hasql
    - hasql-th
    - jwt
    - parser-combinators
    - time
    - vector
    - profunctors
  calc-exe:
    main:                Main.hs
    source-dirs:         examples/calc
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - okapi
  todo-exe:
    main:                Main.hs
    source-dirs:         examples/todo
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - okapi
  servant-exe:
    main:                Main.hs
    source-dirs:         examples/servant
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - okapi
    - lucid
    - parser-combinators
    - servant
    - servant-lucid
    - servant-server

tests:
  okapi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - okapi
