cabal-version: 3.6

name:           okapi
version:        0.2.0.0
synopsis:       A micro web framework based on monadic parsing
description:    Please see the README on GitHub at <https://github.com/monadicsystems/okapi#readme>
category:       Web
homepage:       https://github.com/monadicsystems/okapi#readme
bug-reports:    https://github.com/monadicsystems/okapi/issues
author:         Monadic Systems LLC
maintainer:     tech@monadic.systems
copyright:      2022 Monadic Systems LLC
license:        BSD-3-Clause
license-file:   LICENSE
build-type:     Simple
extra-source-files:
    README.md
    ChangeLog.md

source-repository head
  type: git
  location: https://github.com/monadicsystems/okapi

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:
        Okapi
        Okapi.Application.Client
        Okapi.Application.Server
        Okapi.Artifact.OpenApi
        Okapi.Codec
        Okapi.Contract
        Okapi.Protocol.Request
        Okapi.Protocol.Request.Method
        Okapi.Protocol.Request.Path
        Okapi.Protocol.Request.Query
        Okapi.Protocol.Request.Headers
        Okapi.Protocol.Request.Body
        Okapi.Protocol.Response
        Okapi.Protocol.Response.Status
        Okapi.Protocol.Response.Headers
        Okapi.Protocol.Response.Body
        Okapi.Data
        Okapi.Protocol.Body
        Okapi.Protocol.Headers
        Okapi.Protocol.Headers.Cookies
        Okapi.Protocol.Headers.Attributes
        Okapi.Protocol.Headers.Structured
        Okapi.Protocol.Headers.Structured.Lexer
        Okapi.Protocol.Headers.Structured.BareItem
        Okapi.Protocol.Headers.Structured.Parameters
        Okapi.Protocol.Headers.Structured.Item
        Okapi.Protocol.Headers.Structured.List
        Okapi.Protocol.Headers.Structured.Dictionary
    build-depends:
        base ^>=4.20.0.0,
        aeson,
        bytestring,
        case-insensitive,
        cookie,
        http-api-data,
        http-client,
        http-media,
        http-types,
        insert-ordered-containers,
        lucid,
        optics-core,
        openapi3,
        profunctors,
        scientific,
        text,
        time,
        uuid,
        vector,
        wai
    hs-source-dirs:   src
    default-language: GHC2024

test-suite okapi-examples
    import:           warnings
    type:             exitcode-stdio-1.0
    main-is:          Main.hs
    hs-source-dirs:   test
    build-depends:
        base ^>=4.20.0.0,
        bytestring,
        http-types,
        text,
        okapi
    default-language: GHC2024

test-suite okapi-infer
    import:           warnings
    type:             exitcode-stdio-1.0
    main-is:          Infer.hs
    hs-source-dirs:   test
    build-depends:
        base ^>=4.20.0.0,
        bytestring,
        cookie,
        http-types,
        text,
        okapi
    default-language: GHC2024

test-suite okapi-openapi
    import:           warnings
    type:             exitcode-stdio-1.0
    main-is:          OpenApi.hs
    hs-source-dirs:   test
    build-depends:
        base ^>=4.20.0.0,
        aeson,
        bytestring,
        http-types,
        text,
        okapi,
        openapi3
    default-language: GHC2024

test-suite okapi-roundtrip
    import:           warnings
    ghc-options:      -threaded
    type:             exitcode-stdio-1.0
    main-is:          RoundTrip.hs
    hs-source-dirs:   test
    build-depends:
        base ^>=4.20.0.0,
        bytestring,
        http-client,
        http-types,
        text,
        wai,
        warp,
        okapi
    default-language: GHC2024

test-suite okapi-ex1
    import:           warnings
    ghc-options:      -threaded
    type:             exitcode-stdio-1.0
    main-is:          Ex1.hs
    hs-source-dirs:   test
    build-depends:
        base ^>=4.20.0.0,
        aeson,
        aeson-pretty,
        bytestring,
        http-client,
        openapi3,
        text,
        warp,
        okapi
    default-language: GHC2024

test-suite okapi-ex3
    import:           warnings
    ghc-options:      -threaded
    type:             exitcode-stdio-1.0
    main-is:          Ex3.hs
    hs-source-dirs:   test
    build-depends:
        base ^>=4.20.0.0,
        aeson,
        bytestring,
        http-client,
        http-types,
        mtl,
        openapi3,
        sqlite-simple,
        text,
        warp,
        okapi
    default-language: GHC2024

test-suite okapi-ex2
    import:           warnings
    ghc-options:      -threaded
    type:             exitcode-stdio-1.0
    main-is:          Ex2.hs
    hs-source-dirs:   test
    build-depends:
        base ^>=4.20.0.0,
        bytestring,
        http-client,
        http-types,
        text,
        warp,
        okapi
    default-language: GHC2024

test-suite okapi-subdsl
    import:           warnings
    type:             exitcode-stdio-1.0
    main-is:          SubDsl.hs
    hs-source-dirs:   test
    build-depends:
        base ^>=4.20.0.0,
        bytestring,
        http-types,
        text,
        okapi
    default-language: GHC2024

test-suite okapi-generic
    import:           warnings
    type:             exitcode-stdio-1.0
    main-is:          Generic.hs
    hs-source-dirs:   test
    build-depends:
        base ^>=4.20.0.0,
        bytestring,
        http-types,
        text,
        okapi
    default-language: GHC2024

test-suite okapi-fields
    import:           warnings
    type:             exitcode-stdio-1.0
    main-is:          Fields.hs
    hs-source-dirs:   test
    build-depends:
        base ^>=4.20.0.0,
        bytestring,
        okapi
    default-language: GHC2024

test-suite okapi-query-list
    import:           warnings
    type:             exitcode-stdio-1.0
    main-is:          QueryList.hs
    hs-source-dirs:   test
    build-depends:
        base ^>=4.20.0.0,
        http-types,
        text,
        okapi
    default-language: GHC2024

test-suite okapi-form
    import:           warnings
    type:             exitcode-stdio-1.0
    main-is:          FormBody.hs
    hs-source-dirs:   test
    build-depends:
        base ^>=4.20.0.0,
        bytestring,
        http-api-data,
        text,
        okapi
    default-language: GHC2024

test-suite okapi-content-type
    import:           warnings
    type:             exitcode-stdio-1.0
    main-is:          ContentType.hs
    hs-source-dirs:   test
    build-depends:
        base ^>=4.20.0.0,
        aeson,
        bytestring,
        http-api-data,
        lucid,
        openapi3,
        text,
        okapi
    default-language: GHC2024
